# MOOC Numpy

In [1]:
import numpy as np

In [2]:
a = np.arange(100).reshape(5, 20)

In [3]:
np.savetxt('a.csv', a, fmt='%d', delimiter=',')

In [5]:
np.savetxt('a.csv', a, fmt='%.1f', delimiter=',')

In [6]:
b = np.loadtxt('a.csv', delimiter=',')

In [7]:
b

array([[  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
         11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.],
       [ 20.,  21.,  22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,
         31.,  32.,  33.,  34.,  35.,  36.,  37.,  38.,  39.],
       [ 40.,  41.,  42.,  43.,  44.,  45.,  46.,  47.,  48.,  49.,  50.,
         51.,  52.,  53.,  54.,  55.,  56.,  57.,  58.,  59.],
       [ 60.,  61.,  62.,  63.,  64.,  65.,  66.,  67.,  68.,  69.,  70.,
         71.,  72.,  73.,  74.,  75.,  76.,  77.,  78.,  79.],
       [ 80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,  89.,  90.,
         91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.]])

In [8]:
b = np.loadtxt('a.csv', dtype=np.int, delimiter=',')

In [9]:
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
        37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56,
        57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76,
        77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96,
        97, 98, 99]])

In [10]:
a = np.arange(100).reshape(5, 10, 2)

In [11]:
a.tofile("b.dat", sep=",", format='%d')

In [12]:
c = np.fromfile("b.dat", dtype=np.int, sep=",")

In [13]:
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [14]:
c = np.fromfile("b.dat", dtype=np.int, sep=",").reshape(5, 10, 2)

In [15]:
c

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29],
        [30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49],
        [50, 51],
        [52, 53],
        [54, 55],
        [56, 57],
        [58, 59]],

       [[60, 61],
        [62, 63],
        [64, 65],
        [66, 67],
        [68, 69],
        [70, 71],
        [72, 73],
        [74, 75],
        [76, 77],
        [78, 79]],

       [[80, 81],
        [82, 83],
        [84, 85],
        [86, 87],
        [88, 89],
        [90, 91],
        [92, 93],
        [94, 95],
        [96, 97],
        [98, 99]]])

In [16]:
a = np.arange(100).reshape(5, 10, 2)

In [17]:
np.save("a.npy", a)

In [18]:
b = np.load("a.npy")

In [19]:
b

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29],
        [30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49],
        [50, 51],
        [52, 53],
        [54, 55],
        [56, 57],
        [58, 59]],

       [[60, 61],
        [62, 63],
        [64, 65],
        [66, 67],
        [68, 69],
        [70, 71],
        [72, 73],
        [74, 75],
        [76, 77],
        [78, 79]],

       [[80, 81],
        [82, 83],
        [84, 85],
        [86, 87],
        [88, 89],
        [90, 91],
        [92, 93],
        [94, 95],
        [96, 97],
        [98, 99]]])

In [20]:
a = np.random.rand(3, 4, 5)

In [21]:
a

array([[[ 0.63412005,  0.81299566,  0.29841608,  0.06758126,  0.89878995],
        [ 0.59932862,  0.90740715,  0.09843722,  0.43065027,  0.89686007],
        [ 0.19178989,  0.13387071,  0.56357255,  0.36581432,  0.47317955],
        [ 0.92189578,  0.76122919,  0.59561307,  0.84540874,  0.28723316]],

       [[ 0.34266885,  0.62621397,  0.63442395,  0.86531584,  0.84867638],
        [ 0.12450769,  0.73967248,  0.32794352,  0.71034762,  0.27212402],
        [ 0.79588404,  0.21020315,  0.53543756,  0.6254478 ,  0.0378167 ],
        [ 0.71392551,  0.07696725,  0.79953841,  0.16419314,  0.85074857]],

       [[ 0.47157551,  0.24416162,  0.70272689,  0.43261583,  0.8471505 ],
        [ 0.83573853,  0.5719554 ,  0.06860253,  0.59131763,  0.97525374],
        [ 0.87146256,  0.8195753 ,  0.80735533,  0.34178422,  0.9604674 ],
        [ 0.29123837,  0.3367637 ,  0.16157624,  0.33329089,  0.28096397]]])

In [22]:
sn = np.random.randn(3, 4, 5)

In [23]:
sn

array([[[  1.24453880e+00,  -6.44318919e-01,  -2.93538301e-05,
           1.07565415e+00,  -9.35422048e-01],
        [  1.30887590e+00,  -8.56915273e-01,   1.02799971e+00,
           8.96885503e-01,  -2.74566538e-01],
        [  6.75035675e-01,   2.60484469e-02,   7.01708182e-01,
           6.31579174e-01,  -1.73785576e+00],
        [ -1.01305220e+00,  -7.28466387e-01,   1.24236664e+00,
          -3.58486277e-01,   1.86678595e+00]],

       [[ -1.33867095e+00,  -8.52640981e-03,   1.10096722e+00,
          -1.26678996e+00,   7.75540404e-01],
        [  6.14033917e-01,  -8.04096614e-01,  -1.04404903e-01,
           2.96493598e+00,  -1.78571675e+00],
        [ -1.27304536e+00,   5.70916910e-01,   5.34606091e-01,
           1.21011464e+00,  -4.78660899e-01],
        [ -2.45210192e-02,   5.67893148e-01,   1.71213652e+00,
          -1.80228962e-01,  -3.84122384e-01]],

       [[  1.06576076e+00,   1.33494247e+00,  -1.41107885e-01,
          -3.99201980e-01,  -2.22240261e+00],
        [ -9.18

In [24]:
b = np.random.randint(100, 200, (3,4))

In [25]:
b

array([[122, 190, 139, 160],
       [166, 131, 187, 151],
       [180, 122, 164, 171]])

In [26]:
np.random.seed(10)

In [27]:
np.random.randint(100, 200, (3,4))

array([[109, 115, 164, 128],
       [189, 193, 129, 108],
       [173, 100, 140, 136]])

In [28]:
np.random.seed(10)

In [29]:
np.random.randint(100, 200, (3,4))

array([[109, 115, 164, 128],
       [189, 193, 129, 108],
       [173, 100, 140, 136]])

In [30]:
a = np.random.randint(100, 200, (3,4))

In [31]:
a

array([[116, 111, 154, 188],
       [162, 133, 172, 178],
       [149, 151, 154, 177]])

In [32]:
np.random.shuffle(a)

In [33]:
a

array([[116, 111, 154, 188],
       [149, 151, 154, 177],
       [162, 133, 172, 178]])

In [34]:
np.random.shuffle(a)

In [35]:
a

array([[162, 133, 172, 178],
       [116, 111, 154, 188],
       [149, 151, 154, 177]])

In [2]:
a = np.random.randint(100, 200, (3,4))

In [3]:
a

array([[141, 153, 138, 181],
       [126, 197, 100, 119],
       [180, 153, 164, 136]])

In [4]:
np.random.permutation(a)

array([[126, 197, 100, 119],
       [141, 153, 138, 181],
       [180, 153, 164, 136]])

In [5]:
a

array([[141, 153, 138, 181],
       [126, 197, 100, 119],
       [180, 153, 164, 136]])

In [6]:
b = np.random.randint(100, 200, (8,))

In [7]:
b

array([187, 183, 122, 171, 127, 155, 198, 195])

In [8]:
np.random.choice(b, (3,2), replace=False)

array([[171, 187],
       [127, 198],
       [122, 195]])

In [9]:
np.random.choice(b, (3,2))

array([[127, 195],
       [155, 187],
       [155, 127]])

In [10]:
np.random.choice(b, (3,2), p= b/np.sum(b))

array([[198, 183],
       [127, 155],
       [187, 171]])

In [11]:
u = np.random.uniform(0, 10, (3,4))

In [12]:
u

array([[ 2.63277829,  4.83406713,  8.81392648,  7.95657908],
       [ 7.13531248,  9.41392969,  6.85350385,  1.1544849 ],
       [ 6.0425487 ,  7.87494527,  9.09382486,  5.64155847]])

In [13]:
n = np.random.normal(10, 5, (3,4))

In [14]:
n

array([[ 12.22290416,   0.24363566,  10.52310299,  18.90156802],
       [ 18.53302334,  16.03638184,  17.83187467,   5.46166159],
       [  0.17226648,   5.5241469 ,  10.88881364,  18.95593674]])

In [15]:
a = np.arange(15).reshape(3,5)

In [16]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [17]:
np.sum(a)

105

In [18]:
np.mean(a, axis=1)

array([  2.,   7.,  12.])

In [19]:
np.mean(a, axis=0)

array([ 5.,  6.,  7.,  8.,  9.])

In [20]:
np.average(a, axis=0, weights=[10, 5, 1])

array([ 2.1875,  3.1875,  4.1875,  5.1875,  6.1875])

In [21]:
np.std(a)

4.3204937989385739

In [22]:
np.var(a)

18.666666666666668

In [23]:
b = np.arange(15,0,-1).reshape(3,5)

In [24]:
b

array([[15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

In [26]:
np.max(b)

15

In [27]:
np.argmax(b)

0

In [28]:
np.unravel_index(np.argmax(b), b.shape)

(0, 0)

In [29]:
np.ptp(b)

14

In [30]:
np.median(b)

8.0

In [31]:
a = np.random.randint(0, 20, (5))

In [32]:
a

array([13,  3,  2,  7, 15])

In [33]:
np.gradient(a)

array([-10. ,  -5.5,   2. ,   6.5,   8. ])

In [34]:
b = np.random.randint(0, 20, (5))

In [35]:
b

array([ 9, 18,  8, 18, 13])

In [36]:
np.gradient(b)

array([ 9. , -0.5,  0. ,  2.5, -5. ])

In [37]:
c = np.random.randint(0, 50, (3,5))

In [38]:
c

array([[10, 40, 24, 34,  2],
       [33,  9, 18,  2, 47],
       [25, 25, 48, 49, 10]])

In [39]:
np.gradient(c)

[array([[ 23. , -31. ,  -6. , -32. ,  45. ],
        [  7.5,  -7.5,  12. ,   7.5,   4. ],
        [ -8. ,  16. ,  30. ,  47. , -37. ]]),
 array([[ 30. ,   7. ,  -3. , -11. , -32. ],
        [-24. ,  -7.5,  -3.5,  14.5,  45. ],
        [  0. ,  11.5,  12. , -19. , -39. ]])]

In [40]:
from PIL import Image

In [41]:
import numpy as np

In [42]:
im = np.array(Image.open("E:/code/shali1.jpg"))

In [43]:
print(im.shape, im.dtype)

(1280, 1280, 3) uint8


In [44]:
a = np.array(Image.open("E:/code/shali2.jpg"))

In [45]:
print(a.shape, a.dtype)

(1280, 1280, 3) uint8


In [46]:
b = [255, 255, 155] -a

In [47]:
im = Image.fromarray(b.astype('uint8'))

In [56]:
im.save("E:/code/test.jpg")

In [57]:
a = np.array(Image.open("E:/code/shali1.jpg").convert('L'))

In [58]:
b = 255 - a

In [60]:
im = Image.fromarray(b.astype('uint8'))

In [61]:
im.save("E:/code/test1.jpg")

In [63]:
from PIL import Image
import numpy as np
     
a = np.asarray(Image.open('E:/code/shali2.jpg').convert('L')).astype('float')
     
depth = 10.                      # (0-100)
grad = np.gradient(a)             #取图像灰度的梯度值
grad_x, grad_y = grad               #分别取横纵图像梯度值
grad_x = grad_x*depth/100.
grad_y = grad_y*depth/100.
A = np.sqrt(grad_x**2 + grad_y**2 + 1.)
uni_x = grad_x/A
uni_y = grad_y/A
uni_z = 1./A
     
vec_el = np.pi/2.2                   # 光源的俯视角度，弧度值
vec_az = np.pi/4.                    # 光源的方位角度，弧度值
dx = np.cos(vec_el)*np.cos(vec_az)   #光源对x 轴的影响
dy = np.cos(vec_el)*np.sin(vec_az)   #光源对y 轴的影响
dz = np.sin(vec_el)              #光源对z 轴的影响
     
b = 255*(dx*uni_x + dy*uni_y + dz*uni_z)     #光源归一化
b = b.clip(0,255)
     
im = Image.fromarray(b.astype('uint8'))  #重构图像
im.save('E:/code/shali2HD.jpg')