# 莫烦 Numpy

In [1]:
import numpy as np

In [2]:
array = np.array([[1,2,3],[2,3,4]])  #列表转化为矩阵
print(array)

[[1 2 3]
 [2 3 4]]


In [3]:
print('number of dim:',array.ndim)  # 维度
# number of dim: 2

print('shape :',array.shape)    # 行数和列数
# shape : (2, 3)

print('size:',array.size)   # 元素个数
# size: 6

number of dim: 2
shape : (2, 3)
size: 6


## 创建 array

In [5]:
'''
    array：创建数组
    dtype：指定数据类型
    zeros：创建数据全为0
    ones：创建数据全为1
    empty：创建数据接近0
    arrange：按指定范围创建数据
    linspace：创建线段
'''

'\n    array：创建数组\n    dtype：指定数据类型\n    zeros：创建数据全为0\n    ones：创建数据全为1\n    empty：创建数据接近0\n    arrange：按指定范围创建数据\n    linspace：创建线段\n'

In [6]:
a = np.array([2,23,4])  # list 1d
print(a)

[ 2 23  4]


In [7]:
# 指定数据 dtype
a = np.array([2,23,4],dtype=np.int)
print(a.dtype)

int32


In [8]:
a = np.array([2,23,4],dtype=np.int32)
print(a.dtype)

int32


In [9]:
a = np.array([2,23,4],dtype=np.float)
print(a.dtype)

float64


In [10]:
a = np.array([2,23,4],dtype=np.float32)
print(a.dtype)

float32


## 创建特定数据

In [11]:
a = np.array([[2,23,4],[2,32,4]])  # 2d 矩阵 2行3列
print(a)

[[ 2 23  4]
 [ 2 32  4]]


In [13]:
a = np.zeros((3,4)) # 数据全为0，3行4列
print(a)

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [15]:
a = np.ones((3,4),dtype = np.int)   # 数据为1，3行4列
print(a)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [16]:
a = np.empty((3,4))  # 数据为empty，3行4列
print(a)

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [17]:
# 用 arange 创建连续数组
a = np.arange(10,20,2) # 10-19 的数据，2步长
print(a)

[10 12 14 16 18]


In [18]:
# 使用 reshape 改变数据的形状
a = np.arange(12).reshape((3,4))    # 3行4列，0到11
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [19]:
# 用 linspace 创建线段型数据
a = np.linspace(1,10,20)    # 开始端1，结束端10，且分割成20个数据，生成线段
print(a)

[  1.           1.47368421   1.94736842   2.42105263   2.89473684
   3.36842105   3.84210526   4.31578947   4.78947368   5.26315789
   5.73684211   6.21052632   6.68421053   7.15789474   7.63157895
   8.10526316   8.57894737   9.05263158   9.52631579  10.        ]


In [20]:
# 也能进行 reshape 工作
a = np.linspace(1,10,20).reshape((5,4)) # 更改shape
print(a)

[[  1.           1.47368421   1.94736842   2.42105263]
 [  2.89473684   3.36842105   3.84210526   4.31578947]
 [  4.78947368   5.26315789   5.73684211   6.21052632]
 [  6.68421053   7.15789474   7.63157895   8.10526316]
 [  8.57894737   9.05263158   9.52631579  10.        ]]


# Numpy 基础运算1

In [21]:
a=np.array([10,20,30,40])   # array([10, 20, 30, 40])
b=np.arange(4)              # array([0, 1, 2, 3])
print(a)
print(b)

[10 20 30 40]
[0 1 2 3]


In [22]:
c=a-b  # array([10, 19, 28, 37])
print(a)

[10 20 30 40]


In [23]:
c=a+b   # array([10, 21, 32, 43])
print(c)

[10 21 32 43]


In [24]:
c=a*b   # array([  0,  20,  60, 120])
print(c)

[  0  20  60 120]


In [25]:
c=b**2  # array([0, 1, 4, 9])
print(c)   # 乘方

[0 1 4 9]


In [26]:
c=10*np.sin(a)   # array([-5.44021111,  9.12945251, -9.88031624,  7.4511316 ])
print(c)         # 三角函数

[-5.44021111  9.12945251 -9.88031624  7.4511316 ]


In [27]:
print(b<3)       # array([ True,  True,  True, False], dtype=bool)

[ True  True  True False]


In [28]:
a=np.array([[1,1],[0,1]])
b=np.arange(4).reshape((2,2))
print(a)
print(b)

[[1 1]
 [0 1]]
[[0 1]
 [2 3]]


In [29]:
# 矩阵乘法
c_dot = np.dot(a,b)
print(c_dot)

[[2 4]
 [2 3]]


In [30]:
# 另一种写法
c_dot_2 = a.dot(b)
print(c_dot_2)

[[2 4]
 [2 3]]


### 关于 sum(), min(), max()的使用

In [31]:
a=np.random.random((2,4))
print(a)

[[ 0.88635544  0.38828223  0.89734207  0.94992756]
 [ 0.06042666  0.54481141  0.6403828   0.2035761 ]]


In [33]:
np.sum(a)   # 4.4043622002745959

4.5711042689846604

In [34]:
np.min(a)   # 0.23651223533671784

0.060426656091568165

In [35]:
np.max(a)   # 0.90438450240606416

0.94992756092295705

In [36]:
# 当axis的值为0的时候，将会以列作为查找单元， 
# 当axis的值为1的时候，将会以行作为查找单元
print("a =",a)

a = [[ 0.88635544  0.38828223  0.89734207  0.94992756]
 [ 0.06042666  0.54481141  0.6403828   0.2035761 ]]


In [37]:
print("sum =",np.sum(a,axis=1))

sum = [ 3.1219073   1.44919697]


In [38]:
print("min =",np.min(a,axis=0))

min = [ 0.06042666  0.38828223  0.6403828   0.2035761 ]


In [39]:
print("max =",np.max(a,axis=1))

max = [ 0.94992756  0.6403828 ]


# Numpy 基础运算2

In [50]:
A = np.arange(2,14).reshape((3,4)) 
print(A)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]


In [41]:
# argmin() 和 argmax() 两个函数分别对应着求矩阵中最小元素和最大元素的索引
print(np.argmin(A))    # 0

0


In [42]:
print(np.argmax(A))    # 11

11


In [43]:
# 计算统计中的均值
print(np.mean(A))        # 7.5
print(np.average(A))     # 7.5

7.5
7.5


In [44]:
# mean()函数还有另外一种写法
print(A.mean())          # 7.5

7.5


In [47]:
# 求解中位数的函数
print(np.median(A))       # 7.5

7.5


In [49]:
# 累加函数
print(np.cumsum(A)) 

[ 2  5  9 14 20 27 35 44 54 65 77 90]


In [51]:
# 累差运算函数
# 计算的便是每一行中后一项与前一项之差
print(np.diff(A))   

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [52]:
# 将所有非零元素的行与列坐标分割开，重构成两个分别关于行和列的矩阵
print(np.nonzero(A))    

(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2], dtype=int64), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3], dtype=int64))


In [53]:
# 对所有元素进行仿照列表一样的排序操作
A = np.arange(14,2, -1).reshape((3,4)) 
print(A)

[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]


In [54]:
print(np.sort(A))   

[[11 12 13 14]
 [ 7  8  9 10]
 [ 3  4  5  6]]


In [55]:
# 矩阵的转置有两种表示方法
print(np.transpose(A))    
print(A.T)

[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]
[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]


In [56]:
print(A)
# clip(Array,Array_min,Array_max)  判断矩阵中元素是否有比最小值小的或者比最大值大的元素,转换
print(np.clip(A,5,9))   

[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]
[[9 9 9 9]
 [9 9 8 7]
 [6 5 5 5]]


# Numpy 索引

In [57]:
A = np.arange(3,15)
print(A)
print(A[3])    # 6

[ 3  4  5  6  7  8  9 10 11 12 13 14]
6


In [58]:
# 将矩阵转换为二维的
A = np.arange(3,15).reshape((3,4))
print(A)
print(A[2]) 

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
[11 12 13 14]


In [59]:
# 单独的例子
print(A[1][1])      # 8
print(A[1, 1])      # 8

8
8


In [60]:
# 利用:对一定范围内的元素进行切片操作
print(A[1, 1:3])    # [8 9]

[8 9]


In [61]:
for row in A:
    print(row)

[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]


In [62]:
# 逐列打印
# 对A进行转置；将得到的矩阵逐行输出
for column in A.T:
    print(column)

[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]


In [63]:
A = np.arange(3,15).reshape((3,4))
# 将多维的矩阵进行展开成1行的数列
print(A.flatten())   

[ 3  4  5  6  7  8  9 10 11 12 13 14]


In [64]:
# flat是一个迭代器，本身是一个object属性
for item in A.flat:
    print(item)

3
4
5
6
7
8
9
10
11
12
13
14


# Numpy array 合并

In [65]:
A = np.array([1,1,1])
B = np.array([2,2,2])

print(np.vstack((A,B)))    # vertical stack

[[1 1 1]
 [2 2 2]]


In [70]:
# vertical stack本身属于一种上下合并，即对括号中的两个整体进行对应操作
C = np.vstack((A,B))      
print(np.shape(A),np.shape(C))   

(3,) (2, 3)


In [72]:
D = np.hstack((A,B))       # horizontal stack
print(D)
print(np.shape(A),np.shape(D))    

[1 1 1 2 2 2]
(3,) (6,)


In [73]:
# 如果面对如同前文所述的A序列， 转置操作便很有可能无法对其进行转置（因为A并不是矩阵的属性）
print(A[np.newaxis,:])

[[1 1 1]]


In [74]:
print(A[np.newaxis,:].shape)
print(A[:,np.newaxis])
print(A[:,np.newaxis].shape)
# 将具有3个元素的array转换为了1行3列以及3行1列的矩阵了

(1, 3)
[[1]
 [1]
 [1]]
(3, 1)


In [75]:
A = np.array([1,1,1])[:,np.newaxis]
B = np.array([2,2,2])[:,np.newaxis]
         
C = np.vstack((A,B))   # vertical stack
D = np.hstack((A,B))   # horizontal stack

print(D)

print(A.shape,D.shape)

[[1 2]
 [1 2]
 [1 2]]
(3, 1) (3, 2)


In [76]:
# 针对多个矩阵或序列时，借助concatenate函数更方便
C = np.concatenate((A,B,B,A),axis=0)
print(C)

[[1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [1]
 [1]
 [1]]


In [77]:
D = np.concatenate((A,B,B,A),axis=1)
print(D)
# axis参数很好的控制了矩阵的纵向或是横向打印，相比较vstack和hstack函数显得更加方便

[[1 2 2 1]
 [1 2 2 1]
 [1 2 2 1]]


# Numpy array 分割

In [78]:
A = np.arange(12).reshape((3, 4))
print(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [79]:
# 纵向分割
print(np.split(A, 2, axis=1))

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


In [80]:
# 横向分割
print(np.split(A, 3, axis=0))

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


In [81]:
# 范例的Array只有4列，只能等量对分
print(np.split(A, 3, axis=1))

ValueError: array split does not result in an equal division

### 不等量的分割

In [82]:
print(np.array_split(A, 3, axis=1))

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]


### 其他的分割方式 

In [83]:
print(np.vsplit(A, 3)) #等于 print(np.split(A, 3, axis=0))

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


In [84]:
print(np.hsplit(A, 2)) #等于 print(np.split(A, 2, axis=1))

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


# Numpy copy & deep copy

## = 的赋值方式会带有关联性

In [85]:
a = np.arange(4)
print(a)

b = a
c = a
d = b

[0 1 2 3]


In [86]:
a[0] = 11
print(a)

[11  1  2  3]


In [87]:
b is a  # True
c is a  # True
d is a  # True

True

In [88]:
d[1:3] = [22, 33]   # array([11, 22, 33,  3])
print(a)            # array([11, 22, 33,  3])
print(b)            # array([11, 22, 33,  3])
print(c)            # array([11, 22, 33,  3])

[11 22 33  3]
[11 22 33  3]
[11 22 33  3]


## copy()的赋值方式没有关联性

In [89]:
b = a.copy()    # deep copy
print(b)        # array([11, 22, 33,  3])
a[3] = 44
print(a)        # array([11, 22, 33, 44])
print(b)        # array([11, 22, 33,  3])

[11 22 33  3]
[11 22 33 44]
[11 22 33  3]
